### ISSUE TITLE
selective fetch / event binding

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/backbone-hoodie#3]
as of now, a collection fetches all records of it's model type, and listen to all events of it's model type.

But what if I want a collection that belongs to a parent record? In that case, it should only fetch records of its type, that belong to the respective parent record.

Think of a task list app, where each task is it's own record. How would I fetch only the records of task list A, but not B?

Does that make sense?

**Comment by svnlto** [comment]
Sorry, didn't mean to close this just like that. That functionality wouldn't be covered by this plugin tho. But rather by this one: http://dhruvaray.github.io/backbone-associations/
