### ISSUE TITLE
adding items

### ISSUE THREAD

**Issue by kwakayama** [hoodiehq-archive/backbone-hoodie#4]
Hi.

just tested the connector.
when i add items to the collection, the "add"-event is triggered twice due to:
1. Backbone.hoodie.store.on('add:' ...);
2. Backbone.hoodie.remote.on('add:' ...);

the result is that two models with the same id are located in the collection.
i think it should be checked whether a model should be added or not.

regards

kentaro

**Comment by gr2m** [comment]
do you use the latest version in Master? All we have in there is this:
https://github.com/hoodiehq/backbone-hoodie/blob/master/src/backbone-hoodie.js#L99

Seems correct to me, no duplicated event binding, or do I miss something?
