### ISSUE TITLE
add ability to select store

### ISSUE THREAD

**Issue by svnlto** [hoodiehq-archive/backbone-hoodie#5]
in case of `hoodie-plugin-global-share` i want to be able to connect to a global share `hoodie.global.find etc...` on demand.

**Comment by gr2m** [comment]
you can connect to any store with 

``` js
store = hoodie.open("store-name")
store.connect()
store.on('change', doSomething)
```

Is that what you mean?

**Comment by svnlto** [comment]
yeah, that might do. need to give it a try.
