### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by gr2m** [hoodiehq-archive/backbone-hoodie#8]
I tried a few times but got bit by this:
https://github.com/npm/npm-www/issues/537

And then at the end, by this:
https://github.com/npm/npm-www/issues/537#issuecomment-37686505

Not sure what to do now :/

**Comment by svnlto** [comment]
done.

**Comment by svnlto** [comment]
You probably got the message because you're not on the maintainers list..

**Comment by gr2m** [comment]
if that's the case then the npm error handling is really broken. Could you add me please for the future?

**Comment by svnlto** [comment]
already done that...
