### ISSUE TITLE
Collection not updating on model creation via `save()`

### ISSUE THREAD

**Issue by carltongibson** [hoodiehq-archive/backbone-hoodie#9]
I'm creating a new model instance and then routing to a _detail view_ which pulls its instance from a collection by id. 

The `get(id)` call is failing (returning `undefined`). 

```
var instance = new MyModel();
instance.save();

myModelCollection.get(instance.get('id')); // undefined
```

`Backbone.Collection.prototype.initialize` looks like it's setting up all the right listeners but I'm just not seeing it. 

In order to see the new item I'm needing to call `add()` or `fetch()` on the collection by hand. 

---

My first thought is I'm doing something wrong. (???)

Beyond that though I'm happy to put together a test-case — any favoured conventions?

**Comment by gr2m** [comment]
Hey @carltongibson, I think I know what's wrong here and how to help, I need to look into it but don't have time until Tuesday/Wednesday next week. I'll get back to you unless someone else can help earlier. Sorry to let you wait

**Comment by carltongibson** [comment]
Hey @gr2m — no problem! 

I'm working around it for now. (Which isn't difficult per se) — It would be nice to get the right fix in here though. 

I've yet to put a test together — unless I hear otherwise I'd go for a simple QUnit example. — The bit that I'm pondering is that it will depend on a running CouchDB instance etc (so it won't be much of a _unit_ test...)

**Comment by gr2m** [comment]
@carltongibson Sorry that we still couldn't look into it yet, Carlton. We still have it on our list though, just didn't get it yet. Sorry to let you wait

**Comment by carltongibson** [comment]
@gr2m — thanks for the follow-up. No issues, really — the bug here is easy to work around into the medium term if needs be.

TBH I'd rather all available effort went into the [PouchDB integration](https://github.com/hoodiehq/hoodie.js/issues/8) — that just seems **SOOOOOOOOO** like the way to go... :)

**Comment by gr2m** [comment]
> TBH I'd rather all available effort went into the PouchDB integration — that just seems SOOOOOOOOO like the way to go... :)

oh yeah! We're setting the stage for that right now. Can't wait to join forces with Pouch!

**Comment by gr2m** [comment]
You need to set `MyModel.type` if you want the magical adding of models to collections, see https://github.com/hoodiehq/backbone-hoodie/blob/master/src/backbone-hoodie.js#L97

I'm not sure if that's the right way of doing it though. What I see others doing is to defined own Collection Classes, e.g. check out the Firebase's Backbone adapter:
https://github.com/firebase/backfire/blob/gh-pages/backbone-firebase.js

Also not that our current approach would work only if you want to have all models of one type in one collection. What I ended up doing in my app is to have an initialize method that listens to the hoodie events:

``` ls
initialize: function() {
    var type = this.model.prototype.type;
    Backbone.hoodie.store.on('change:'+type, _.bind(this.handleChange, this));
  },
```

And then have custom logic to determine if that change should be handled by this collection:

``` js
handleChange: function(eventType, properties, options) {
    var model;
    if (options.backbone) return;

    // custom logic here, e.g. check of relation
    if (properties.parentId !== this.parent().id) return;

    switch(eventType) {
      case 'add':
        this.add(properties, {remote: true});
        break;
      case 'update':
        model = this.get(properties.id);
        model.set(properties, {remote: true});
        break;
      case 'remove':
        this.remove(properties, {remote: true});
        break;
    }
  }
```

Note the `if (options.backbone) return` check. That makes sure that changes made by the current user through Backbone Logic do not trigger same events again.

Hope that helps. But if you're interested into making this adapter more proper, @svnlto and me are also very interested in doing that, just didn't get to it yet

**Comment by gr2m** [comment]
Just out of my head, what could imagine is something like this

``` js
Backbone.Collection.extend({
  sync: hoodie.backbone.genereateSync('todo')
})
```

Unless I miss anything, that should be enough. Within generateSync, the code would look something like (a bit simplified)

``` js
function generateSync(filter) {
  var collectionStore = hoodie.store(filter);

  return function sync(method, modelOrCollection, options) {
    var id = modelOrCollection.id;
    var attributes = modelOrCollection.toJSON();

    switch (method) {
    case 'read':
      if (id) {
        store.find(id).then(options.success, options.error);
      } else {
        store.findAll().then(options.success, options.error);
      }
      break;
    case 'create':
      store.add(attributes, options).then(options.success, options.error)
      break;
    case 'update':
      store.updateOrAdd(id, attributes).then(options.success, options.error)
      break;
    case 'delete':
      store.remove(id).then(options.success, options.error);
    }
  } 
}
```

`hoodie.store` can be called as function and returns a scoped store, either scoped by type `hoodie.store('todo')` or by type and id `hoodie.store('todo', '123')`. What I could imagine is to extend `hoodie.store` so that it also accepts a filter function, like this:

``` js
hoodie.store( function filter(object) {
  return object.type === 'todo' && object.taskListId === '123'
});
```

What you think?

**Comment by gr2m** [comment]
Ideally, when I try to come up with the coolest Dreamcode from a Backbone Developer perspective, the above code should maybe read

``` js
// simple filtering by type
Backbone.Hoodie.Collection.extend({
  type: 'todo'
})
// alternatively filtering with a function, or combined
Backbone.Hoodie.Collection.extend({
  type: 'todo',
  filter: function (object) { return object.todoListId === '123' }
})
```

In case we need Models (do we?), that could work

``` js
// simple filtering by type
Backbone.Hoodie.Model.extend({
  type: 'config'
})
```

Also, `backbone-hoodie` really should be a Hoodie Plugin :)

**Comment by carltongibson** [comment]
Hey @gr2m — Sorry for the slow reply — I've been working at the other end of the stack :)

There's a lot here that I need to try out, and think about, and work out what's best, and see if that generalises. 

First thoughts: 
- I am setting `type` on the model. The README implies that should be enough, but it's not, yet — hence opening the issue.
- I don't want to set `type` on the collection. I'm already setting `model`. 

Other than that though, I get the idea. I'll have a play.
